theme: jekyll-theme-leap-day
title: Eduardo C. Garrido-Merchán
description: Artificial Intelligence Teacher Assistant and researcher at the Machine Learning Group, EPS-UAM
github:
  is_project_page: false
